# Generated by Django 5.2.15 on 2026-06-24 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0003_device_collector_enabled_device_last_collected_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('subnets', models.JSONField(blank=True, default=list, help_text='Lista de CIDRs: ["10.0.0.0/24", "192.168.0.0/16"]', verbose_name='sub-redes')),
                ('snmp_community', models.CharField(blank=True, default='', max_length=100, verbose_name='comunidade SNMP (override)')),
                ('snmp_version', models.CharField(choices=[('v2c', 'SNMPv2c'), ('v3', 'SNMPv3')], default='v2c', max_length=10, verbose_name='versão SNMP')),
                ('max_workers', models.PositiveSmallIntegerField(default=5, verbose_name='threads simultâneas')),
                ('timeout', models.PositiveSmallIntegerField(default=5, verbose_name='timeout (s)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'perfil de descoberta',
                'verbose_name_plural': 'perfis de descoberta',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('username', models.CharField(blank=True, default='', max_length=100, verbose_name='usuário')),
                ('encrypted_password', models.TextField(blank=True, default='', verbose_name='senha (criptografada)')),
                ('encrypted_enable_secret', models.TextField(blank=True, default='', verbose_name='enable secret (criptografado)')),
                ('snmp_community', models.CharField(blank=True, default='', max_length=100, verbose_name='comunidade SNMP')),
                ('snmp_version', models.CharField(choices=[('v2c', 'SNMPv2c'), ('v3', 'SNMPv3')], default='v2c', max_length=10, verbose_name='versão SNMP')),
                ('vendor_hint', models.CharField(blank=True, default='', help_text='Restringe esta credencial a um fabricante específico', max_length=20, verbose_name='fabricante (opcional)')),
                ('priority', models.IntegerField(default=0, verbose_name='prioridade')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'credencial de rede',
                'verbose_name_plural': 'credenciais de rede',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CollectorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('success', 'Sucesso'), ('partial', 'Parcial'), ('failed', 'Falha')], default='pending', max_length=20, verbose_name='status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='iniciado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizado em')),
                ('discovered_count', models.IntegerField(default=0, verbose_name='descobertos')),
                ('collected_count', models.IntegerField(default=0, verbose_name='coletados')),
                ('analyzed_count', models.IntegerField(default=0, verbose_name='analisados')),
                ('failed_count', models.IntegerField(default=0, verbose_name='falhas')),
                ('summary', models.TextField(blank=True, default='', verbose_name='resumo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.discoveryprofile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'execução do coletor',
                'verbose_name_plural': 'execuções do coletor',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('action', models.CharField(choices=[('snmp_discovery', 'Descoberta SNMP'), ('ssh_collect', 'Coleta SSH'), ('analyze', 'Análise')], max_length=20, verbose_name='ação')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('success', 'Sucesso'), ('failed', 'Falha'), ('skipped', 'Pulado')], default='pending', max_length=20, verbose_name='status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizado em')),
                ('log', models.TextField(blank=True, default='', verbose_name='log')),
                ('error', models.TextField(blank=True, default='', verbose_name='erro')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device', verbose_name='equipamento')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='collector.collectorrun', verbose_name='execução')),
            ],
            options={
                'verbose_name': 'tarefa do coletor',
                'verbose_name_plural': 'tarefas do coletor',
                'ordering': ['run', 'action', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='discoveryprofile',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.networkcredential', verbose_name='credencial'),
        ),
    ]
