# Generated by Django 5.2.15 on 2026-06-19 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Atenção'), ('critical', 'Crítico')], default='info', max_length=10, verbose_name='severidade')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='categoria')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_issues', to='config_archive.configsnapshot', verbose_name='snapshot')),
            ],
            options={
                'verbose_name': 'análise/issue',
                'verbose_name_plural': 'análises/issues',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectedCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_type', models.CharField(choices=[('l3', 'Circuito L3'), ('vlan_transport', 'VLAN de Transporte'), ('qinq', 'QinQ'), ('bgp', 'BGP com Cliente'), ('transport_mikrotik', 'Transporte MikroTik'), ('olt', 'Circuito de OLT'), ('bng', 'BNG/BAS'), ('l2vpn', 'L2VPN/VSI/VPLS'), ('other', 'Outro')], max_length=30, verbose_name='tipo de circuito')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='detalhes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_circuits', to='config_archive.configsnapshot', verbose_name='snapshot')),
            ],
            options={
                'verbose_name': 'circuito detectado',
                'verbose_name_plural': 'circuitos detectados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_data', models.JSONField(verbose_name='dados parseados')),
                ('parser_version', models.CharField(default='1.0', max_length=20, verbose_name='versão do parser')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_configs', to='config_archive.configsnapshot', verbose_name='snapshot')),
            ],
            options={
                'verbose_name': 'configuração parseada',
                'verbose_name_plural': 'configurações parseadas',
                'ordering': ['-created_at'],
            },
        ),
    ]
