# Generated by Django 5.2.15 on 2026-06-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisissue',
            name='code',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='código'),
        ),
        migrations.AddField(
            model_name='analysisissue',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='detectedcircuit',
            name='circuit_type',
            field=models.CharField(choices=[('l3', 'Circuito L3'), ('l3_transit', 'Trânsito L3'), ('vlan_transport', 'VLAN de Transporte'), ('qinq', 'QinQ'), ('bgp', 'BGP com Cliente'), ('transport_mikrotik', 'Transporte MikroTik'), ('olt', 'Circuito de OLT'), ('bng', 'BNG/BAS'), ('l2vpn', 'L2VPN/VSI/VPLS'), ('other', 'Outro')], max_length=30, verbose_name='tipo de circuito'),
        ),
    ]
