# Generated by Django 5.2.15 on 2026-06-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisissue_code_analysisissue_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedcircuit',
            name='circuit_type',
            field=models.CharField(choices=[('l3', 'Circuito L3'), ('l3_transit', 'Trânsito L3'), ('vlan_transport', 'VLAN de Transporte'), ('qinq', 'QinQ'), ('qinq_transport', 'Transporte QinQ'), ('bgp', 'BGP com Cliente'), ('transport_mikrotik', 'Transporte MikroTik'), ('olt', 'Circuito de OLT'), ('bng', 'BNG/BAS'), ('l2vpn', 'L2VPN/VSI/VPLS'), ('l2vpn_vsi', 'L2VPN com VSI'), ('other', 'Outro')], max_length=30, verbose_name='tipo de circuito'),
        ),
    ]
