# Generated by Django 5.2.15 on 2026-06-19 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_detectedcircuit_circuit_type'),
        ('config_archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('bng', 'BNG/BAS'), ('aaa', 'Autenticação AAA'), ('radius', 'Servidor RADIUS'), ('ip_pool', 'Pool de Endereços IP'), ('subscriber_access', 'Acesso de Assinante')], max_length=30, verbose_name='tipo de serviço')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='nome')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('confidence', models.FloatField(default=0.0, verbose_name='confiança')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_services', to='config_archive.configsnapshot', verbose_name='snapshot')),
            ],
            options={
                'verbose_name': 'serviço detectado',
                'verbose_name_plural': 'serviços detectados',
                'ordering': ['-confidence', '-created_at'],
            },
        ),
    ]
