# Generated by Django 5.2.15 on 2026-06-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_detectedservice'),
        ('config_archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='título')),
                ('summary', models.TextField(blank=True, default='', verbose_name='resumo')),
                ('diff_data', models.JSONField(blank=True, default=dict, verbose_name='dados da comparação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('base_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_base', to='config_archive.configsnapshot', verbose_name='snapshot base')),
                ('target_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_target', to='config_archive.configsnapshot', verbose_name='snapshot alvo')),
            ],
            options={
                'verbose_name': 'comparação de configurações',
                'verbose_name_plural': 'comparações de configurações',
                'ordering': ['-created_at'],
            },
        ),
    ]
