# Generated by Django 5.2.15 on 2026-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_configcomparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedservice',
            name='service_type',
            field=models.CharField(choices=[('bng', 'BNG/BAS'), ('aaa', 'Autenticação AAA'), ('radius', 'Servidor RADIUS'), ('ip_pool', 'Pool de Endereços IP'), ('subscriber_access', 'Acesso de Assinante'), ('snmp', 'SNMP'), ('ntp', 'NTP'), ('syslog', 'Syslog'), ('management_access', 'Acesso Administrativo'), ('local_user', 'Usuário Local')], max_length=30, verbose_name='tipo de serviço'),
        ),
    ]
