# Generated by Django 5.2.15 on 2026-06-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_alter_detectedservice_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedservice',
            name='service_type',
            field=models.CharField(choices=[('bng', 'BNG/BAS'), ('aaa', 'Autenticação AAA'), ('radius', 'Servidor RADIUS'), ('ip_pool', 'Pool de Endereços IP'), ('subscriber_access', 'Acesso de Assinante'), ('snmp', 'SNMP'), ('ntp', 'NTP'), ('syslog', 'Syslog'), ('management_access', 'Acesso Administrativo'), ('local_user', 'Usuário Local'), ('l2_switching', 'Comutação L2'), ('vlan_service', 'VLAN'), ('stp', 'STP/RSTP/MSTP'), ('ospf', 'OSPF'), ('isis', 'ISIS'), ('mpls', 'MPLS'), ('mpls_ldp', 'MPLS LDP'), ('vrf', 'VRF/VPN-instance'), ('l3vpn', 'L3VPN MPLS'), ('vpnv4', 'BGP VPNv4'), ('qos', 'QoS / Qualidade de Serviço'), ('traffic_policy', 'Traffic Policy'), ('qos_car', 'CAR / Controle de Banda'), ('nat', 'NAT / PAT'), ('nat_outbound', 'NAT Outbound (PAT)'), ('nat_static', 'NAT Estático'), ('nat_server', 'NAT Server / Port Forward'), ('ipv6', 'IPv6'), ('bgp_ipv6', 'BGP IPv6 Unicast'), ('vpnv6', 'BGP VPNv6'), ('ospfv3', 'OSPFv3'), ('isis_ipv6', 'ISIS IPv6'), ('bng_advanced', 'BNG Avançado'), ('bas_interface', 'BAS Interface'), ('subscriber_domain', 'Domínio de Assinante'), ('aaa_scheme', 'AAA Scheme'), ('radius_group', 'Grupo RADIUS'), ('pppoe', 'PPPoE Server'), ('virtual_template', 'Virtual-Template'), ('ppp_access', 'PPP Subscriber Access'), ('bfd', 'BFD / Fast Convergence'), ('graceful_restart', 'Graceful Restart'), ('nsr', 'NSR / Non-Stop Routing'), ('multicast', 'Multicast Routing'), ('pim', 'PIM Sparse Mode'), ('igmp', 'IGMP / IPTV Access'), ('igmp_snooping', 'IGMP Snooping'), ('mld', 'MLD IPv6 Multicast'), ('evpn_vxlan', 'EVPN / VXLAN'), ('segment_routing', 'Segment Routing / SRv6'), ('mpls_te', 'MPLS-TE / RSVP-TE'), ('cgnat', 'CGNAT Avançado'), ('msdp', 'MSDP'), ('telemetry', 'Telemetria / Streaming')], max_length=30, verbose_name='tipo de serviço'),
        ),
    ]
