# Generated by Django 5.2.15 on 2026-06-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('vendor', models.CharField(choices=[('huawei', 'Huawei'), ('zte', 'ZTE'), ('datacom', 'Datacom'), ('cisco', 'Cisco'), ('mikrotik', 'MikroTik'), ('other', 'Outro')], default='huawei', max_length=20, verbose_name='fabricante')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'equipamento',
                'verbose_name_plural': 'equipamentos',
                'ordering': ['name'],
            },
        ),
    ]
