# Generated by Django 5.2.15 on 2026-06-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='plataforma'),
        ),
        migrations.AddField(
            model_name='device',
            name='role',
            field=models.CharField(blank=True, choices=[('core', 'Core'), ('distribution', 'Distribuição'), ('access', 'Acesso'), ('border', 'Borda'), ('pe', 'PE'), ('p', 'P'), ('router', 'Roteador'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('bng', 'BNG'), ('other', 'Outro')], default='', max_length=30, verbose_name='função'),
        ),
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='site'),
        ),
    ]
