# Generated by Django 5.2.15 on 2026-06-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_platform_device_role_device_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='collector_enabled',
            field=models.BooleanField(default=True, verbose_name='coleta automática'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_collected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última coleta'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_discovered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última descoberta'),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_port',
            field=models.PositiveIntegerField(default=161, verbose_name='porta SNMP'),
        ),
        migrations.AddField(
            model_name='device',
            name='ssh_port',
            field=models.PositiveIntegerField(default=22, verbose_name='porta SSH'),
        ),
    ]
