# Generated by Django 5.2.15 on 2026-06-20 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=50, verbose_name='ação')),
                ('object_type', models.CharField(blank=True, default='', max_length=50, verbose_name='tipo de objeto')),
                ('object_id', models.CharField(blank=True, default='', max_length=50, verbose_name='ID do objeto')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='user-agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'log de auditoria',
                'verbose_name_plural': 'logs de auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
