# Generated by Django 5.2.15 on 2026-06-23 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0019_add_gpon_olt_service_type'),
        ('config_archive', '0002_configsnapshot_captured_at_and_more'),
        ('devices', '0002_device_platform_device_role_device_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_a', models.CharField(max_length=200, verbose_name='Interface A')),
                ('interface_b', models.CharField(max_length=200, verbose_name='Interface B')),
                ('discovery_method', models.CharField(choices=[('manual', 'Manual'), ('subnet', 'Subrede'), ('description', 'Descrição')], default='manual', max_length=20)),
                ('confidence', models.CharField(choices=[('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('discovered', 'Descoberto'), ('confirmed', 'Confirmado'), ('ignored', 'Ignorado')], default='discovered', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_a', to='devices.device')),
                ('device_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_b', to='devices.device')),
            ],
            options={
                'verbose_name': 'Enlace entre dispositivos',
                'verbose_name_plural': 'Enlaces entre dispositivos',
            },
        ),
        migrations.CreateModel(
            name='VlanDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.IntegerField(verbose_name='VLAN ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('device_count', models.IntegerField(default=0, verbose_name='Dispositivos')),
                ('interface_count', models.IntegerField(default=0, verbose_name='Interfaces')),
                ('first_seen_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device')),
            ],
            options={
                'verbose_name': 'Definição de VLAN',
                'verbose_name_plural': 'Definições de VLAN',
                'ordering': ['session', 'vlan_id'],
            },
        ),
        migrations.CreateModel(
            name='VlanTrackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Sessão de rastreamento',
                'verbose_name_plural': 'Sessões de rastreamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VlanTrackingIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(blank=True, max_length=200)),
                ('severity', models.CharField(choices=[('critical', 'Crítico'), ('high', 'Alto'), ('medium', 'Médio'), ('low', 'Baixo'), ('info', 'Informativo')], default='medium', max_length=10)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device')),
                ('vlan_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vlan_tracking.vlandefinition')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_issues', to='vlan_tracking.vlantracksession')),
            ],
            options={
                'verbose_name': 'Issue de rastreamento',
                'verbose_name_plural': 'Issues de rastreamento',
                'ordering': ['-severity', 'code'],
            },
        ),
        migrations.CreateModel(
            name='VlanPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_interface', models.CharField(max_length=200)),
                ('to_interface', models.CharField(max_length=200)),
                ('tagged', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('partial', 'Parcial'), ('suspected', 'Suspeito')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('from_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlan_paths_from', to='devices.device')),
                ('to_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlan_paths_to', to='devices.device')),
                ('via_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vlan_tracking.devicelink')),
                ('vlan_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='vlan_tracking.vlandefinition')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlan_paths', to='vlan_tracking.vlantracksession')),
            ],
            options={
                'verbose_name': 'Caminho de VLAN',
                'verbose_name_plural': 'Caminhos de VLAN',
            },
        ),
        migrations.CreateModel(
            name='VlanEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=200, verbose_name='Interface')),
                ('endpoint_type', models.CharField(choices=[('access', 'Porta Access'), ('subinterface_l3', 'Subinterface L3'), ('l2vpn_vsi', 'L2VPN VSI'), ('bas', 'BAS/BNG'), ('qinq_edge', 'QinQ Edge'), ('unknown', 'Desconhecido')], default='unknown', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('vlan_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='vlan_tracking.vlandefinition')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlan_endpoints', to='vlan_tracking.vlantracksession')),
            ],
            options={
                'verbose_name': 'Ponto terminal de VLAN',
                'verbose_name_plural': 'Pontos terminais de VLAN',
            },
        ),
        migrations.AddField(
            model_name='vlandefinition',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlan_definitions', to='vlan_tracking.vlantracksession'),
        ),
        migrations.AddField(
            model_name='devicelink',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='vlan_tracking.vlantracksession'),
        ),
        migrations.CreateModel(
            name='VlanTrackDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('role_hint', models.CharField(choices=[('core', 'Core'), ('distribution', 'Distribuição'), ('access', 'Acesso'), ('pe', 'PE'), ('p', 'P'), ('bng', 'BNG'), ('unknown', 'Desconhecido')], default='unknown', max_length=20, verbose_name='Função sugerida')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlan_track_entries', to='devices.device')),
                ('parsed_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.parsedconfig')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_archive.configsnapshot')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_devices', to='vlan_tracking.vlantracksession')),
            ],
            options={
                'verbose_name': 'Dispositivo na sessão',
                'verbose_name_plural': 'Dispositivos na sessão',
                'ordering': ['session', 'order'],
                'constraints': [models.UniqueConstraint(fields=('session', 'device', 'snapshot'), name='uq_vlan_track_device_per_session')],
            },
        ),
        migrations.CreateModel(
            name='VlanInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=200, verbose_name='Interface')),
                ('vlan_id', models.IntegerField(verbose_name='VLAN ID')),
                ('port_mode', models.CharField(choices=[('access', 'Access'), ('trunk', 'Trunk'), ('hybrid', 'Hybrid'), ('subinterface', 'Subinterface'), ('qinq', 'QinQ'), ('l2vpn', 'L2VPN'), ('bas', 'BAS'), ('unknown', 'Desconhecido')], default='unknown', max_length=20, verbose_name='Modo')),
                ('tagged', models.BooleanField(default=True, verbose_name='Tagged')),
                ('pvid', models.BooleanField(default=False, verbose_name='PVID')),
                ('source', models.CharField(choices=[('access_vlan', 'Access VLAN'), ('trunk_allowed', 'Trunk allowed'), ('hybrid_tagged', 'Hybrid tagged'), ('hybrid_untagged', 'Hybrid untagged'), ('dot1q', 'Subinterface dot1q'), ('qinq', 'QinQ'), ('vsi', 'L2VPN VSI'), ('bas_user_vlan', 'BAS user-vlan')], default='access_vlan', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('raw_metadata', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_archive.configsnapshot')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlan_interfaces', to='vlan_tracking.vlantracksession')),
            ],
            options={
                'verbose_name': 'Interface VLAN',
                'verbose_name_plural': 'Interfaces VLAN',
                'indexes': [models.Index(fields=['session', 'vlan_id'], name='vlan_tracki_session_8aa2bd_idx'), models.Index(fields=['session', 'device'], name='vlan_tracki_session_4da639_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vlandefinition',
            constraint=models.UniqueConstraint(fields=('session', 'vlan_id'), name='uq_vlan_definition_per_session'),
        ),
        migrations.AddConstraint(
            model_name='devicelink',
            constraint=models.UniqueConstraint(fields=('session', 'device_a', 'interface_a', 'device_b', 'interface_b'), name='uq_device_link_unique'),
        ),
    ]
