# Generated by Django 5.2.15 on 2026-06-23 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_archive', '0002_configsnapshot_captured_at_and_more'),
        ('devices', '0002_device_platform_device_role_device_site'),
        ('vlan_tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelink',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último visto'),
        ),
        migrations.AddField(
            model_name='devicelink',
            name='raw_evidence',
            field=models.TextField(blank=True, verbose_name='Evidência bruta'),
        ),
        migrations.AddField(
            model_name='devicelink',
            name='remote_hostname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hostname remoto'),
        ),
        migrations.AddField(
            model_name='devicelink',
            name='remote_interface',
            field=models.CharField(blank=True, max_length=200, verbose_name='Interface remota'),
        ),
        migrations.AlterField(
            model_name='devicelink',
            name='discovery_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('lldp', 'LLDP'), ('csv', 'CSV'), ('subnet', 'Subrede'), ('description', 'Descrição')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='TopologyEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('lldp', 'LLDP'), ('csv', 'CSV'), ('manual', 'Manual'), ('description', 'Descrição'), ('subnet', 'Subrede')], default='lldp', max_length=20)),
                ('raw_text', models.TextField(verbose_name='Texto bruto')),
                ('parsed_data', models.JSONField(blank=True, null=True, verbose_name='Dados parseados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='vlan_tracking.vlantracksession')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_archive.configsnapshot')),
            ],
            options={
                'verbose_name': 'Evidência de topologia',
                'verbose_name_plural': 'Evidências de topologia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='devicelink',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vlan_tracking.topologyevidence', verbose_name='Evidência'),
        ),
    ]
