# Generated by Django 5.2.15 on 2026-06-19 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_config', models.TextField(verbose_name='configuração bruta')),
                ('vendor', models.CharField(blank=True, default='', help_text='Detectado automaticamente ou informado pelo usuário', max_length=20, verbose_name='fabricante')),
                ('source', models.CharField(choices=[('paste', 'Colado'), ('upload', 'Upload de arquivo'), ('api', 'API')], default='paste', max_length=20, verbose_name='origem')),
                ('notes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='devices.device', verbose_name='equipamento')),
            ],
            options={
                'verbose_name': 'snapshot de configuração',
                'verbose_name_plural': 'snapshots de configuração',
                'ordering': ['-created_at'],
            },
        ),
    ]
