# Generated by Django 5.2.15 on 2026-06-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configsnapshot',
            name='captured_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora da captura no equipamento', null=True, verbose_name='capturado em'),
        ),
        migrations.AddField(
            model_name='configsnapshot',
            name='config_hash',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text='SHA256 do conteúdo normalizado, usado para deduplicação', max_length=64, verbose_name='hash SHA256'),
        ),
        migrations.AddField(
            model_name='configsnapshot',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='configsnapshot',
            name='is_baseline',
            field=models.BooleanField(default=False, verbose_name='baseline'),
        ),
        migrations.AddField(
            model_name='configsnapshot',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='nome'),
        ),
    ]
