# Generated by Django 5.2.15 on 2026-06-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_archive', '0002_configsnapshot_captured_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsnapshot',
            name='source',
            field=models.CharField(choices=[('paste', 'Colado'), ('upload', 'Upload de arquivo'), ('api', 'API'), ('auto', 'Coleta automática')], default='paste', max_length=20, verbose_name='origem'),
        ),
    ]
